### ISSUE TITLE
code highlight for php does not work fine

### ISSUE THREAD

**Issue by hotdog5225** [natfarleydev/anki-auto-markdown#9]
when i write php code begin with **```php**  , it does not hightlight the php syntax. 

the backgroud of the code block is dark. show as the pic below. 

![image](https://user-images.githubusercontent.com/11531561/93299335-7515d700-f827-11ea-9d3f-f1f7fbc0bd5c.png)

![image](https://user-images.githubusercontent.com/11531561/93299189-40098480-f827-11ea-9d5b-bcb976e1da37.png)

what i want is like this : (written in go)
![image](https://user-images.githubusercontent.com/11531561/93299433-a393b200-f827-11ea-9a72-8a6b727ed71a.png)

![image](https://user-images.githubusercontent.com/11531561/93299418-9aa2e080-f827-11ea-97b0-07af989da173.png)

**Comment by natfarleydev** [comment]
Can you paste the HTML for the top image please? (Ctrl-Shift-x while focussed on the box should bring it up). I recently changed the way the markdown is parsed to preserve images when converting to markdown but it sometimes has odd effects when code is pasted in.

Otherwise it might be an out of date pygments dependency (easily fixed 🤞)

**Comment by natfarleydev** [comment]
@hotdog5225 #10 (and the fix just after it) should fix this now, let me know if it's a problem again and I'll reopen.

**Comment by fxmarty** [comment]
Hello @natfarleydev , thank you for the addon I think it is great.

I still have this problem, the addon being downloaded from https://ankiweb.net/shared/info/15061497 . Maybe it is not up to date.

Here's a screenshot of my card: 
![card](https://user-images.githubusercontent.com/9808326/105732906-41fbf680-5f31-11eb-8045-a6fd04c365fd.png)

And how it is displayed:
![display](https://user-images.githubusercontent.com/9808326/105733022-5c35d480-5f31-11eb-85ca-20e0e52d52c6.png)

Here is my style for the card, but I think it has no influence:
```
.card {
 font-family: lato;
 font-size: 22px;
 text-align: center;
 color: black;
 background-color: white;
}
```

Secondly, I would suggest to ignore `text-align: center` argument for the code blocks. What do you think?

Thanks again!

**Comment by fxmarty** [comment]
@natfarleydev Any idea?

**Comment by natfarleydev** [comment]
Hi @fxmarty, 
The `color: black` is what's responsible for changing the colour of the text in the code block so if you remove that it should be fine; I would recommend not setting `color` or `background-color` in the card CSS if possible and letting the app manage those attributes via dark/not-dark mode. 

As for setting `text-align`, it's a nice idea but easier said than done as it's not possible to 'ignore' certain CSS attributes within the code block, only override them. If you want, you can set this up in your CSS by doing 

```css
pre {
  text-align: left;
}
```

Also, you can enable syntax highlighting by putting the language name straight after the triple backtick, like

```
```python

```


If you have any troubles feel free to raise a new ticket and I can add something to the README.

**Comment by JackElsey** [comment]
Thanks for creating this add-on.

I'm experiencing the same issue with dark text. Removing `color: black` as suggested didn't resolve the problem. My current card styling is below.

```
.latex{
 zoom:70%;
}
.card {
 font-family: arial;
 font-size: 20px;
 text-align: left;
}
img{vertical-align:middle;}
```

I can side-step this issue by specifying what programming language the code block is for, but that's not ideal. Any ideas?

**Comment by natfarleydev** [comment]
Hi @JackElsey, 
If you want the background of code blocks to be white, you can change the `colorScheme` value in the configuration for the plugin to a white backround scheme like `"xcode"` e.g.:
![image](https://user-images.githubusercontent.com/1312119/115672673-b2a18c00-a343-11eb-9396-9e34a84aef5e.png)

I personally use Dark mode by default everywhere, so the current plugin ships with the monokai colour scheme which is likely the cause of your issues. 

Out of interest, why is it that you don't specify the programming language for code blocks?

**Comment by JackElsey** [comment]
Thank you, that fixed the issue for me.

>Out of interest, why is it that you don't specify the programming language for code blocks?

Sometimes I have cards with pseudocode. It's just nice to have the option.
